# Generated by Django 4.2.6 on 2024-06-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="punto_carnaval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coord_lat", models.FloatField()),
                ("coord_lng", models.FloatField()),
                ("titulo", models.CharField(max_length=255)),
                ("direccion", models.CharField(max_length=255)),
                ("imagen_ruta", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="puntos_recorrido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud_rc", models.FloatField(blank=True)),
                ("longitud_rc", models.FloatField(blank=True)),
            ],
        ),
    ]
