# Generated by Django 4.2.6 on 2024-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="puntos_recorrido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitud_rc", models.FloatField(blank=True)),
                ("longitud_rc", models.FloatField(blank=True)),
            ],
        ),
    ]
