# Generated by Django 4.2.6 on 2023-12-18 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_diario"),
    ]

    operations = [
        migrations.CreateModel(
            name="pagomes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio_pago", models.PositiveIntegerField(blank=True)),
                ("mes_pago", models.PositiveIntegerField(blank=True)),
                ("retrasos", models.PositiveIntegerField(blank=True)),
                ("salidas", models.PositiveIntegerField(blank=True)),
                (
                    "tot_descento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
