# Generated by Django 4.2.6 on 2024-06-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_punto_conoce"),
    ]

    operations = [
        migrations.AddField(
            model_name="punto_conoce",
            name="detalles",
            field=models.CharField(default="default", max_length=255),
        ),
    ]
